name: watermark_unique_example
description: "Demonstrates how to use the watermark_unique plugin."
version: "1.0.0"
homepage: https://github.com/engineer-unknown/watermark_unique

environment:
  sdk: '>=3.2.5 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  image_picker: 1.1.2
  path_provider: 2.1.5

  watermark_unique:
    path: ../

  cupertino_icons: ^1.0.8

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true